### ISSUE TITLE
Please

### ISSUE THREAD

**Issue by Romxn1** [jellydn/dapp-token-ico#435]
Hi, sorry for writing here. 
Please write the instructions in more detail how to run this app
Thnx

**Comment by jellydn** [comment]
Hi there,

You could see that guideline for running on local on readme file https://github.com/jellydn/dapp-token-ico#hardhat-guideline Let me know if that works for you.

**Comment by jellydn** [comment]
I also record a video about this repo on my channel https://www.youtube.com/watch?v=9fmViThaMGk&list=PLOdXIcVPTyB-jyB4UmrwncHDK0mgl-Ex-&index=4
