### ISSUE TITLE
Cannot upload on vercel or netift

### ISSUE THREAD

**Issue by snnicketh** [jellydn/dapp-token-ico#682]
### Describe the bug

I have deployed the contracts on mainnet but cannot be used on thr app. i cant upload the web on vercel or netify, its crashing on build

### Reproduction

Deployment

### System Info

```Shell
Error
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Just FYI 
<img width="959" alt="image" src="https://user-images.githubusercontent.com/870029/202463042-86269f90-766b-4631-b187-e2fd3422a955.png">
